[build]
[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist/server"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
